maidsafe/safe-app-csharp

- CakeHelperScripts/InspectCode.cake
- tools/packages.config
**Change**
- Cake script older package (v0.27.2) is not working (not sure why) that's why CI is not running properly. Upgrading the cake version fixes the issue.
- Newer NuGet package for JetBrains.ReSharper.CommandLineTools is reporting suppressed resharper rules as suggestions/warning, so setting it to an older version.
> fix/ci: update cake version and set JetBrains.ReSharper.CommandLineTools version

- CakeHelperScripts/NativeScriptDownloader.cake
Remove .a files for android and desktop project.
Fixes #28
> refactor/safe_app_csharp: Remove .a files from platform libs

- SafeApp.AppBindings/AppBindings.cs
Update AppBindings to use UIntPtrCb delegate.
> Use FfiResultULongFromUIntPtrCb delegate instead of FfiResultULongCb delegate

- CakeHelperScripts/NativeScriptDownloader.cake
- README.md
- SafeApp.AppBindings.Android/Android.targets
- SafeApp.Tests.Android/SafeApp.Tests.Android.csproj
Fixes: #31 
**Changes**
- Remove from cake files (download and unzipping x86 android native libraries)
- Update project structure to not include x86 libs
- Update readme file
- Update nuspec file (used for NuGet packaging)
> Remove x86 support for android.

- SafeApp.Tests/MiscTest.cs
- SafeApp.Tests/MutableDataTests.cs
- SafeApp.Tests/NFS.cs
- SafeApp/NativeHandle.cs
fixes: #51 
**Changes**
- Added AnyOne NativeHandle - Use to insert permissions for all users
- Added EmptyMDataEntries NativeHandle - Use to put mutable data with zero entries
- Added EmptyMDataPermissions NativeHandle - Use to put mutable data with zero permissions
- Marked Zero NativeHandle as Obsolete
> Refactor/NativeHandle: Add seperate null handles

- CakeHelperScripts/DesktopTest.cake
- README.md
- appveyor.yml
- build.cake
Update the cake script to generate and upload code coverage to [coveralls.io](https://coveralls.io/)
- Generate code coverage report using [OpenCover](https://cakebuild.net/dsl/opencover/)
- Upload the code coverage report to coveralls.io using [Cake.Coveralls](https://cake-contrib.github.io/Cake.Coveralls)
> feat/CodeCoverage: Upload code coverage report to coveralls.io

- .gitignore
- CakeHelperScripts/DesktopTest.cake
- SafeApp.AppBindings.iOS/Properties/AssemblyInfo.cs
- SafeApp.AppBindings.iOS/SafeApp.AppBindings.iOS.csproj
- SafeApp.AppBindings/AppBindings.Manual.cs
- SafeApp.AppBindings/AppBindings.cs
- SafeApp.MockAuthBindings.iOS/SafeApp.MockAuthBindings.iOS.csproj
- SafeApp.MockAuthBindings/AuthBindings.Manual.cs
- SafeApp.MockAuthBindings/AuthBindings.cs
- SafeApp.Tests/AuthTests.cs
- SafeApp.Tests/CryptoTests.cs
- SafeApp.Tests/MiscTest.cs
- SafeApp.Tests/MutableDataTests.cs
- SafeApp.Tests/NFS.cs
- SafeApp.Tests/Utils.cs
- SafeApp.Utilities/Helpers.cs
- SafeApp.Utilities/IAppBindings.Manual.cs
- SafeApp.sln.DotSettings
- SafeApp/MData/MDataPermissions.cs
- SafeApp/Misc/Crypto.cs
- SafeApp/Misc/NFS.cs
- SafeApp/NativeHandle.cs
- SafeApp/SafeAppPtr.cs
- SafeApp/Session.cs
Fixes: #26 
We previously added the StyleCop and enforced the coding standards in the solution. The files are shared between the .NET Standard project and platform projects and hence the conditional statements in iOS projects never went through the StyleCop rules.
In this PR, I'm adding the StyleCop analyzer to the iOS AppBinding and MockAuthBinding projects to prevent this in future. 
The `.DotSettings` file used by the Reshaper wasn't in sync as there is no good tool available to sync the style format between StyleCop and Resharper. This PR includes a manually updated `.DotSettings` file which may need further changes in future.
This PR also includes the change in the build script to make it work with updated Appveyor .NET Core runtime, as the new test result file generated by `dotnet …
> reformat/resharper: Updated .DotSettings file & add stylecop for iOS projects

- CakeHelperScripts/iOSTest.cake
- SafeApp/SafeAppPtr.cs
When a new Session object is created, that is using following public constructor and the `_appPtr` is set to IntPtr.Zero using SafeAppPtr public constructor.
**Session.cs**
```
// Session constructor
private Session()
{
IsDisconnected = true;
_appPtr = new SafeAppPtr();
}
```
**SafeAppPtr.cs**
```
public IntPtr Value { get; private set; }
public SafeAppPtr(IntPtr appPtr)
{
Value = appPtr;
}
// SafeAppPtr constructor
public SafeAppPtr() : (IntPtr.Zero)
{
}
```
So, if a Session object is out of scope/disposed/destructed the FreeApp function is called in `Session.cs` and we are checking it the `_appPtr` is already equal to `IntPtr.Zero` that means we don't have to free  the memory.
**`FreeApp()` in `Session.cs`**
```
private void FreeApp()
{
if (_appPtr == IntPtr.Zero)
{
return;
} …
```
> fix/SafeApp: remove IntPtr.Zero check from SafeAppPtr

- CakeHelperScripts/DesktopTest.cake
- appveyor.yml
Disabling the deployment of API docs since the new API doesn't have any documentation also the code coverage reporting is disabled in this otherwise this will overwrite the coverage for the `master`/`stable` branch.
> chore/CI: disable doc deployment and coverage report on AppVeyor

- CakeHelperScripts/NativeScriptDownloader.cake
- SafeApp.AppBindings/AppBindings.cs
- SafeApp.AppBindings/SafeApp.AppBindings.csproj
- SafeApp.AppBindings/Targets/Android.targets
- SafeApp.AppBindings/Targets/NetCore.targets
- SafeApp.AppBindings/Targets/iOS.targets
- SafeApp.Core/SafeApp.Core.csproj
- SafeApp.MockAuthBindings/AuthBindings.cs
- SafeApp.MockAuthBindings/SafeApp.MockAuthBindings.csproj
- SafeApp.nuspec
- SafeApp/SafeApp.csproj
- Tests/SafeApp.Tests.Android/SafeApp.Tests.Android.csproj
- Tests/SafeApp.Tests.Core/SafeApp.Tests.Core.csproj
- Tests/SafeApp.Tests.Framework/SafeApp.Tests.Framework.csproj
- Tests/SafeApp.Tests.iOS/SafeApp.Tests.iOS.csproj
**Changes**
- Downloading new libs from S3
- Using `safe_api` instead of `safe_app` and also it seems better choice then `safe_api_ffi`
**Note**
- Android libs are just copy of linux ones, I will upload correct libs on Monday
- All the libs are mock only, non-mock will also be uploaded next week
- The links will have to be updated later next week once we have Jenkins setup
> New libs from s3

- SafeApp.AppBindings/Abstraction/IAppBindings.cs
- SafeApp.AppBindings/AppBindings.HighLevel.cs
- SafeApp.AppBindings/AppBindings.cs
- SafeApp.Core/AppTypes.HighLevel.cs
- SafeApp.Core/AppTypes.cs
- SafeApp.Core/BindingUtils.cs
- SafeApp.MockAuthBindings/Abstraction/IAuthBindings.cs
- SafeApp.MockAuthBindings/AuthBindings.cs
- SafeApp.MockAuthBindings/AuthTypes.cs
- SafeApp.MockAuthBindings/Authenticator.cs
- SafeApp/API/Fetch.cs
- SafeApp/API/XorEncoder.cs
- SafeApp/Session.cs
IntPtr is passed with ref keyword, which gives the address of the pointer and not the value of it, leading to `receiver is gone` error on native side.
FIX #111
> fix: do not pass IntPtr with ref keyword

- SafeApp.AppBindings/Abstraction/IAppBindings.cs
- SafeApp.AppBindings/AppBindings.HighLevel.cs
- SafeApp.AppBindings/SafeApp.AppBindings.csproj
- SafeApp.Core/AppTypes.Manual.cs
- SafeApp/API/Keys.cs
- SafeApp/Session.cs
- Tests/SafeApp.Tests/KeyTest.cs
- Tests/SafeApp.Tests/SafeApp.Tests.projitems
Fixes : #95
This adds `Keys` APIs.
Following APIs are added:
- `GenerateKeyPairAsync`
- `CreateKeysAsync`
- `KeysCreatePreloadTestCoinsAsync`
- `KeysBalanceFromSkAsync`
- `KeysBalanceFromUrlAsync`
- `ValidateSkForUrlAsync`
- `KeysTransferAsync`
> New API Integration - Keys

- SafeApp/API/Fetch.cs
- SafeApp/API/Files.cs
- SafeApp/API/Keys.cs
- SafeApp/API/Wallet.cs
The private `IntPtr _appPtr` field is made `readonly` and of type `SafeAppPtr`.
Fixes #113
> refactor/api: use readonly app pointer

- SafeApp.AppBindings/AppBindings.HighLevel.cs
The callback was previously updated to adjust to changes in bindings, but the name wasn't.
Fixes #130
> Rename callback delegate

- SafeApp.AppBindings/Abstraction/IAppBindings.cs
- SafeApp.AppBindings/AppBindings.HighLevel.cs
- SafeApp.Core/AppTypes.HighLevel.cs
- SafeApp/API/XorEncoder.cs
- Tests/SafeApp.Tests/FetchTest.cs
- Tests/SafeApp.Tests/NrsTest.cs
- Tests/SafeApp.Tests/XorUrlEncoderTest.cs
This will replace `ulong` and `ushort` representation of the content type and data type, with enum.
Additional structs have been added to `AppTypes.HighLevel.cs`. Seems a little bit "bloaty" to duplicate all those properties just for a single prop type change, but perhaps not many simple options there now.
NB: `ContentType.MediaType` is also conveying media type natively, but we're currently not capturing that value.
Fixes: #133
> refactor/bindings: use enums for content type and data type

- SafeApp.AppBindings/SafeApp.AppBindings.csproj
- SafeApp.Core/SafeApp.Core.csproj
- SafeApp.MockAuthBindings/SafeApp.MockAuthBindings.csproj
- SafeApp.nuspec
- SafeApp/SafeApp.csproj
- Tests/SafeApp.Tests.Android/Properties/AndroidManifest.xml
- Tests/SafeApp.Tests.Core/SafeApp.Tests.Core.csproj
- Tests/SafeApp.Tests.Framework/SafeApp.Tests.Framework.csproj
fixes: #82 
**Changes:**
- Updated supported platform version
- .NET Standard 1.3 -> 2.0
- .NET Core 1.0 -> 2.2
- .NET Framework 4.6 -> 4.7.2
- MonoAndroid 4.4 -> 5.0
- Updated `.nuspec` file
- Remove `System.TupleValue` package
> chore/SafeApp: update the platform support versions

- Tests/SafeApp.Tests/FetchTest.cs
- Tests/SafeApp.Tests/FilesTest.cs
- Tests/SafeApp.Tests/KeyTest.cs
- Tests/SafeApp.Tests/NrsTest.cs
- Tests/SafeApp.Tests/SafeApp.Tests.projitems
- Tests/SafeApp.Tests/TestUtils.cs
- Tests/SafeApp.Tests/Validations.cs
- Tests/SafeApp.Tests/WalletTests.cs
- Tests/SafeApp.Tests/XorUrlEncoderTest.cs
Validations can be re-used between tests. Additionally, there is a lot of duplicate and excess code for various parts of the tests, which is cleaned up and made more space efficient, readable and terse with this commit.
Fixes: #125
> refactor/tests: clean up tests

- Build/NativeScriptDownloader.cake
- Tests/SafeApp.Tests.Core/SafeApp.Tests.Core.csproj
- Tests/SafeApp.Tests/FetchTest.cs
- Tests/SafeApp.Tests/MiscTest.cs
- Tests/SafeApp.Tests/NrsTest.cs
- Tests/SafeApp.Tests/TestUtils.cs
- Tests/SafeApp.Tests/Validations.cs
- Tests/SafeApp.Tests/log.toml
fixes: #160 
fixes: #161
- **SetConfigurationFilePathAsync** test is added to ensure the native libs has this native function available.
-  **RustLoggerTest** test is ignored on Win + .NET Core env. I'm not sure why this one is not working, will need SCL help to figure this out.
- Added the rust logging util function which can be manually called if required when running the tests locally.
> Use latest native libs and remove ignore attribute for inspect and fetch tests

- Build/NativeScriptDownloader.cake
- SafeApp.Core/AppTypes.HighLevel.cs
- Tests/SafeApp.Tests/FetchTest.cs
**Changes related to: https://github.com/maidsafe/safe-api/pull/326**
_**Note:** CI will fail as the native libs need to be updated to use the latest. Will update the PR later._
> refactor/bindings: use FilesMap structs instead of json strings

- README.md
Alpha 2 network has now been taken down so these tutorials are no longer accurate.
> docs/readme: update readme to remove links to Alpha-2 tutorials

- SafeApp.nuspec
The new MSBuild version has changed the build output format from `MonoAndroid{API}\{API}\BuildFiles` to `MonoAndorid{API}\BuildFiles` which is not causing an issue on the CI and we aren't able to genrate the NuGet package. 
This PR fixes that issue.
> fix/package fix nuspec file to generate NuGet package

- Build/NativeScriptDownloader.cake
- Build/get_release_description.sh
- README.md
- SafeApp.AppBindings/AppBindings.cs
- SafeApp.AppBindings/Targets/Android.targets
- SafeApp.AppBindings/Targets/NetCore.targets
- SafeApp.AppBindings/Targets/iOS.targets
- SafeApp.nuspec
- SafeAuthenticator/AuthBindings.cs
- Tests/SafeApp.Tests.Android/SafeApp.Tests.Android.csproj
- Tests/SafeApp.Tests.Core/SafeApp.Tests.Core.csproj
- Tests/SafeApp.Tests.Framework/SafeApp.Tests.Framework.csproj
- Tests/SafeApp.Tests.iOS/SafeApp.Tests.iOS.csproj
- Tests/SafeApp.Tests/log.toml
- UpdateBindings.md
Also includes renaming `SAFE` to `Safe` in the readme.
It is expected that CI will fail on this PR, and any others after it is merged, until a new version of the sn_api, sn_cli & sn_ffi are released with the new naming conventions --> https://dev.azure.com/maidsafe/SafeApp/_build/results?buildId=1913&view=logs&j=b5c3680a-75af-5c19-dc38-e2ccb7d74d37&t=a1fe8770-d8e3-5fd2-7165-f056bd7cb277&l=266
> chore(deps): update to reference renamed sn_api, sn_cli and sn_ffi
