maidsafe/safe-app-csharp

- SafeApp.AppBindings.Android/SafeApp.AppBindings.Android.csproj
- SafeApp.AppBindings/AppBindings.cs
- SafeApp.MockAuthBindings.Android/SafeApp.MockAuthBindings.Android.csproj
- SafeApp.Tests.Android/SafeApp.Tests.Android.csproj
- SafeApp.Tests/CipherOptTests.cs
- SafeApp.Utilities/IAppBindings.cs
- SafeApp.Utilities/NativeDelegates.cs
- SafeApp/Misc/CipherOpt.cs
Changes to the CipherOpt.cs by adding CipherOptSymmetric and CipherOptAsymmetric functions along with the test cases.
> feat/[Cipher-opt]: Added Native functions to the Cipher-Opt file along with the valid test cases.

- CHANGELOG.MD
- SafeApp.nuspec
Nuspec version change from 0.0.2 to 0.1.0
> version change to 0.1.0

- CHANGELOG.MD
- SafeApp.AppBindings/AppBindings.Manual.cs
- SafeApp.AppBindings/AppBindings.cs
- SafeApp.MockAuthBindings/AuthBindings.Manual.cs
- SafeApp.MockAuthBindings/AuthBindings.cs
- SafeApp.nuspec
Fixes the delegate garbage collection issue in safe_app and mock_auth bindings.
> MAID-2880 - Fix garbage collected callback delegates

- SafeApp.MockAuthBindings.Android/SafeApp.MockAuthBindings.Android.csproj
- SafeApp.MockAuthBindings.Desktop/SafeApp.MockAuthBindings.Desktop.csproj
- SafeApp.MockAuthBindings.iOS/SafeApp.MockAuthBindings.iOS.csproj
- SafeApp.MockAuthBindings/AuthTypes.Manual.cs
- SafeApp.MockAuthBindings/SafeApp.MockAuthBindings.csproj
- SafeApp.Utilities/AppTypes.cs
- SafeApp.Utilities/BindingUtils.cs
- SafeApp.Utilities/IAppBindings.Manual.cs
- SafeApp.Utilities/IAppBindings.cs
- SafeApp.Utilities/SafeApp.Utilities.csproj
- SafeApp/NativeHandle.cs
- SafeApp/SafeApp.csproj
fixes: #44 
**Changes**
- Update projects to generate XML files to include in NuGet package.
- Update docs for the native handle and some other classes
> docs/SafeApp: update project settings to generate xml docs

- CHANGELOG.MD
- SafeApp.nuspec
> version change to 0.2.0

- README.md
- UpdateBindings.md
- codeowners
**Changes**
- Updated README file
- Added file containing binding update instructions
**Preview**
https://github.com/ravinderjangra/safe_app_csharp/blob/update-readme/README.md
>  docs/README: Add more documentation to the README

- README.md
> docs/SafeApp: udpate broken blog link

- SafeApp.AppBindings/Abstraction/IAppBindings.Manual.cs
- SafeApp.AppBindings/Abstraction/IAppBindings.cs
- SafeApp.AppBindings/AppBindings.Manual.cs
- SafeApp.AppBindings/AppBindings.cs
- SafeApp.Core/AppTypes.Manual.cs
- SafeApp.Core/AppTypes.cs
- SafeApp.Core/BindingUtils.cs
- SafeApp.Core/Helpers.cs
- SafeApp.MockAuthBindings/AuthTypes.Manual.cs
- SafeApp/IData/IData.cs
- SafeApp/MData/MData.cs
- SafeApp/MData/MDataEntries.cs
- SafeApp/MData/MDataEntryActions.cs
- SafeApp/MData/MDataInfoActions.cs
- SafeApp/Misc/Crypto.cs
- SafeApp/Misc/NFS.cs
- SafeApp/Session.cs
Replaced all instances of `List<byte>` with `byte[]`.  
Simple fix for https://github.com/maidsafe/safe_app_csharp/issues/39#issue-382903507 until https://github.com/maidsafe/safe_bindgen/issues/42#issue-429699029 has been solved.
> Byte array fix

- SafeApp.AppBindings/Abstraction/IAppBindings.cs
- SafeApp.AppBindings/AppBindings.HighLevel.cs
- SafeApp.AppBindings/AppBindings.cs
- SafeApp.Core/AppTypes.HighLevel.cs
- SafeApp.Core/AppTypes.Manual.cs
- SafeApp.Core/AppTypes.cs
- SafeApp.Core/BindingUtils.cs
- SafeApp.MockAuthBindings/AuthBindings.cs
- SafeApp.MockAuthBindings/AuthTypes.Manual.cs
- SafeApp/API/Fetch.cs
- SafeApp/API/XorEncoder.cs
- SafeApp/Session.cs
- Tests/SafeApp.Tests/AuthTest.cs
- Tests/SafeApp.Tests/SafeApp.Tests.projitems
- Tests/SafeApp.Tests/TestUtils.cs
- Tests/SafeApp.Tests/XorUrlEncoderTest.cs
fixes: #105 
fixes: #103 
fixes: #104 
**APIs Added**
- Connect
- Fetch
- Xorurl Encoder
**Pending**
- Unit tests
_**Note:** delete `Ignore` attribute from the TextFixture to run the tests locally._
> New API integration - Connect, Fetch, XorUrl Encoder

- SafeApp.AppBindings/Abstraction/IAppBindings.cs
- SafeApp.AppBindings/AppBindings.HighLevel.cs
- SafeApp.Core/AppTypes.HighLevel.cs
- SafeApp/API/Wallet.cs
- SafeApp/Session.cs
- Tests/SafeApp.Tests/SafeApp.Tests.projitems
- Tests/SafeApp.Tests/TestUtils.cs
- Tests/SafeApp.Tests/WalletTests.cs
Fixes: #101 
The Wallet API with the docs and tests.
> Add Wallet API

- Directory.Build.props
- SafeApp.sln
We want C# lang version 7.3 as solution-wide default.
Fixes #128
> chore: set default lang version

- SafeApp.Core/AppTypes.HighLevel.cs
- Tests/SafeApp.Tests/FetchTest.cs
- Tests/SafeApp.Tests/NrsTest.cs
- Tests/SafeApp.Tests/XorUrlEncoderTest.cs
PR to reflect API changes: https://github.com/maidsafe/safe-cli/pull/275
> refactor/bindings: add xorurl field for fetch data types

- SafeApp.Core/AppTypes.HighLevel.cs
- SafeApp.Core/SafeApp.Core.csproj
- SafeApp.Core/Serialization.cs
- SafeApp.MockAuthBindings/SafeApp.MockAuthBindings.csproj
- SafeApp/API/Fetch.cs
- SafeApp/API/Files.cs
- SafeApp/API/Keys.cs
- SafeApp/API/Nrs.cs
- SafeApp/API/Wallet.cs
- SafeApp/API/XorEncoder.cs
- SafeApp/SafeApp.csproj
- SafeApp/Session.cs
> Add XML documentation for the new API

- SafeApp.AppBindings/Targets/NetCore.targets
fixes: #77 
**Note:** May need some other changes in future. Not sure ATM as it depends on how the package will work with this change.
> chore/SafeApp: update .NET Core target file

- Build/NativeScriptDownloader.cake
- SafeApp.AppBindings/SafeApp.AppBindings.csproj
- Tests/SafeApp.Tests/KeyTest.cs
> chore/nativelibs: download native libs from S3

- SafeApp.AppBindings/Abstraction/IAppBindings.cs
- SafeApp.AppBindings/AppBindings.HighLevel.cs
- SafeApp/API/Fetch.cs
- Tests/SafeApp.Tests/FetchTest.cs
> Add Inspect API

- Tests/SafeApp.Tests/TestUtils.cs
_**Note:** Android tests will fail on CI because the native libs from S3 aren't working. Tested locally._
> fix/tests: update test file dir path for Android

- SafeApp.AppBindings/AppBindings.HighLevel.cs
- SafeApp.Core/AppTypes.HighLevel.cs
- Tests/SafeApp.Tests/FetchTest.cs
> refactor/fetchTest: divide the fetch and inspect tests into two

- Build/NativeScriptDownloader.cake
- Build/iOSTest.cake
- SafeApp.Core/AppTypes.HighLevel.cs
- Tests/SafeApp.Tests/NrsTest.cs
> chore/bindings: update cake to use latest libs and remove cap field from the native strutures

- SafeApp.AppBindings/Abstraction/IAppBindings.cs
- SafeApp.AppBindings/AppBindings.cs
- SafeApp/Session.cs
> feat/bindings: add setconfigpath API

- Build/Utility.cake
- Build/iOSTest.cake
- Tests/SafeApp.Tests.iOS/AppDelegate.cs
Working locally, let's check if working on remote CI as well :smile:
> fix/tests: use simple file search for the iOS tests instead of TCP client

- Build/NativeScriptDownloader.cake
- SafeApp.AppBindings/Abstraction/IAppBindings.cs
- SafeApp.AppBindings/AppBindings.HighLevel.cs
- SafeApp.AppBindings/AppBindings.cs
- SafeApp.MockAuthBindings/Abstraction/IAuthBindings.cs
- SafeApp.MockAuthBindings/AuthBindings.cs
- SafeApp.MockAuthBindings/Authenticator.cs
- SafeApp/Session.cs
- Tests/SafeApp.Tests/TestUtils.cs
> Add auth_app API, update connect API and remove deprecated SCL bindings & APIs

- Build/azure-pipeline.yml
**Note:** Some changes will be required in the Azure-DevOps to start using this pipeline. Will be possible once this is merged so that the Azure can search for the build pipeline definition file.
> move Azure Pipeline from UI based setup to the repo

- SafeApp.Core/AppConstants.cs
- Tests/SafeApp.Tests/TestUtils.cs
> chore/bindings: update SymNonceLen to 16 from 24

- Build/NativeScriptDownloader.cake
- SafeApp.AppBindings/Abstraction/IAppBindings.cs
- SafeApp.AppBindings/AppBindings.cs
- SafeApp/API/Files.cs
- Tests/SafeApp.Tests/FilesTest.cs
based on: https://github.com/maidsafe/safe-api/pull/548
> refactor/SafeApp: use FilesMap struct instead of json strings
